### ISSUE TITLE
Opacity transition

### ISSUE THREAD

**Issue by og2t** [StreakYC/react-smooth-collapse#1]
Hi StreakYC,

Thanks for this little nib, it saved my life today :) Would you consider adding opacity transition as well? It would be nice to collapse and fade at the same time.

Cheers.

**Comment by Macil** [comment]
You could use a normal CSS transition rule for that. You could change the classname on the contents when it's opened or closed.

**Comment by og2t** [comment]
Great suggestion, it worked fine :) Thanks!
