### ISSUE TITLE
Display:none optional

### ISSUE THREAD

**Issue by PeterKottas** [StreakYC/react-smooth-collapse#13]
It would be great to have display none optional, among other things, this would allow one so achieve #12

**Comment by PeterKottas** [comment]
Maybe it would make sense if collapsedHeight: undefined would set the display to none (also default) while 0 would keep it visible. Just thinking out loud

**Comment by Macil** [comment]
What's the use of avoiding display:none if the height is 0? Is this only for the case where overflow:hidden is being overridden?

**Comment by PeterKottas** [comment]
Yeah pretty much

**Comment by Macil** [comment]
A className prop exists now that can be used to override the display:none rule. Let me know if that doesn't work for your use case.
