### ISSUE TITLE
Classes for expanded and collapsed

### ISSUE THREAD

**Issue by PeterKottas** [StreakYC/react-smooth-collapse#14]
It would help styling of the inner component if classnames of the expander were set to collapsed or expanded accordingly.

**Comment by Macil** [comment]
Hard-coding some class names in the component is something I want to avoid; there's cases where it's inappropriate, such as when the component is used in a page that already has styling for the hard-coded classnames. I'd rather users used wrapper divs with their own class names, or if #8 were to be implemented, then there should be additional expandedClassName (+ maybe expandedStyle) props.

**Comment by PeterKottas** [comment]
Ok fair enough
