### ISSUE TITLE
z-index of elements within collapsible

### ISSUE THREAD

**Issue by willbryk720** [StreakYC/react-smooth-collapse#18]
Thanks for making the awesome library!

One thing I noticed is that elements inside the collapsible have lower z-indices than anything outside the collapsible. I'm using a dropdown component from semantic-react in a collapsible, and the dropdown gets cutoff by items outside the collapsible. Do you know of a way to force the elements within the collapsible to have a higher z-index?

**Comment by Macil** [comment]
I assume the dropdown is using position:absolute, and its element is contained within react-smooth-collapse's children. You could solve your issue by either setting SmoothCollapse's allowOverflowWhenOpen prop to true (but your dropdown will be clipped during collapse/uncollapse animations), or by using a dropdown component which will place its element outside of react-smooth-collapse's children (like https://github.com/StreakYC/react-float-anchor).

**Comment by willbryk720** [comment]
Sweet, that worked! Thank you so much! The open/close animation occurs so quickly that it's unnoticeable.
