### ISSUE TITLE
Expanding dynamic generated content?

### ISSUE THREAD

**Issue by edbras** [StreakYC/react-smooth-collapse#20]
Does it also expand dynamic generated content? 
That is: children items of a parent items are retrieved from the backend and should then be shown in smooth expandable way.

**Comment by Macil** [comment]
You can put anything inside of it. The components on the inside don't even render until the SmoothCollapse component has been expanded at least once, so if you have a component on the inside which makes a network request to load content in its componentDidMount method, that won't be called until the SmoothCollapse component has been expanded.

**Comment by edbras** [comment]
Let me see if I understand you correctly. 
What I want to do: as soon as a persoon clicks the parent node, the children nodes are loaded from the backend through Fetch and has to be shown smoothly expanded and then collapsed when the user clicks the parent again.
How can this be realised through smoothCollapse?

**Comment by Macil** [comment]
You could put all of the content-loading-related code into a separate component (`MyComponentThatFetchesContentOnMount` here) which loads content on mount, and then do something like this:

```js
  render() {
    return (
      <div>
        <div>
          <input
              type="button"
              value={this.state.expanded ? 'Hide' : 'Show'}
              onClick={() => this._toggle()}
          />
        </div>
        <SmoothCollapse expanded={this.state.expanded}>
          <MyComponentThatFetchesContentOnMount />
        </SmoothCollapse>
      </div>
    );
  }
```

You might want to look at the example for more information: https://github.com/StreakYC/react-smooth-collapse/blob/master/example/Example.js

**Comment by Macil** [comment]
I'm going to close this issue. Feel free to reply if you still want any help with using react-smooth-collapse.
