### ISSUE TITLE
Should pass additional props (or at least id) to the main <div> element

### ISSUE THREAD

**Issue by eemeli** [StreakYC/react-smooth-collapse#22]
As the title states. I'd be happy to put in a PR given guidance on your preference on allowing just the wrapper's `id` to be set, or for any uncaptured props to be assigned to the main `<div>`.

As context for this request, we need to assign an `id` value to a DOM element (currently an otherwise unnecessary wrapping `<div>`) in order to use it as a target of ARIA properties, for accessibility.

**Comment by Macil** [comment]
Thanks, this is in 2.1.0 now.
