### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by iyn** [StreakYC/react-smooth-collapse#4]
Hey,

I just want to say: thank you for creating this project! I use it extensively and I love it, this is by far the best component of this type.

Quick question: would you say that the component is finished and do you plan to add/change something?

**Comment by Macil** [comment]
Good to hear that it's useful for you!

I don't see the project changing much going forward besides making sure it stays compatible with the current version of React. It does one thing well, and I haven't thought up a way or need to generalize it further. A few weeks ago I added the `collapsedHeight` feature. I haven't thought of any similar features like that (which need special cooperation from this component) to add, but that's the sort of thing that would be added if anything.

The project does follow the [semver standard](http://semver.org/), so if any breaking changes are made, we'll make sure to bump the major version number up.

**Comment by iyn** [comment]
I like that attitude - do one thing, and do it great :).

Again - thank you very much for sharing this project!
