### ISSUE TITLE
Sluggish animation on mobile

### ISSUE THREAD

**Issue by molul** [StreakYC/react-smooth-collapse#45]
I don't know if it's a known issue or if I'm doing something wrong, but the animation is not that smooth on mobile. 

Live site: https://www.luismorcilloluque.com/en/skills (check on mobile or reduce the browser window to show the collapse buttons).

It plays reasonable smooth on my MacMini, but not at all on my Xiaomi phone. 

The code:
```
            <CollapseButton
              title={skills?.name[lang]}
              expanded={open}
              toggleFunc={toggleOpen}
            />

          <SmoothCollapse expanded={open} heightTransition=".5s ease-out">
            <div className="justify-center grid gap-2 grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4 mt-4">
              {skills?.data?.map((skill, index) => {
                return (
                  <div key={index} className="items-center ">
                    <SkillItem nombre={skill.name} puntuacion={skill.level} />
                  </div>
                );
              })}
            </div>
          </SmoothCollapse>
```

**Comment by Macil** [comment]
No obvious mistakes stand out to me here.

This component mostly just sets a transition rule on the height property and changes the height, so performance issues will most likely have more to do with that than any specifics of this component. (I expect you'd see the same sluggishness if you replaced SmoothCollapse here with `<div style={{transition: "height .5s ease-out", height: open ? "200px" : "20px}}>`.)

Animating the height of an element causes the browser to have to reflow the document on each frame (so subsequent items can reposition), so it can be an expensive operation on complex pages or on underpowered devices. (As opposed to animations on transform rules, which are much more efficient, but don't the page to reflow for the element's new size, which wouldn't work well for your design here.)

To optimize this, I wonder if it would be possible to simplify the styling rules for this part of the page to make reflows cheaper. I do notice you're using grid-based styling inside of each of the collapsible sections on the page, which aren't doing much when the page is in its thin mobile-view mode, and I wonder about the performance impact of this. You should try testing the performance of a simplified version of this page where each collapsible section of the page was completely empty; if that helps then it's a sign that simplifying the CSS inside of each one could help your performance, but if it doesn't help then it's a sign that's the wrong track.

**Comment by molul** [comment]
Will try that. Thanks! :)
